sudo: required

services:
  - docker

before_install:
  - cd tfserving/resnet
  - docker build -t niacainfosys/cloud-tfserving-resnet:1.14.0 -f tfserving-resnet-1.14.0.Dockerfile .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push niacainfosys/cloud-tfserving-resnet:1.14.0