apiVersion: v1
kind: Pod
metadata:
  generateName: od-api-client-
spec:
  containers:
  - name: yolo-container
    image: niacainfosys/cloud-od-api-client
    imagePullPolicy: Always
    command: [sh, -c]
    args: ["python3 client.py --iterations=2 --users=2"]
  restartPolicy: Never