apiVersion: v1
kind: Pod
metadata:
  generateName: yolo-api-client-
spec:
  containers:
  - name: yolo-container
    image: niacainfosys/cloud-tfserving-yolo-client
    imagePullPolicy: Always
    command: [sh, -c]
    args: ["python3 http_multiclient.py --users=2 --batch_size=2 --iterations=2"]
  restartPolicy: Never