apiVersion: v1
kind: Pod
metadata:
  generateName: yolo-multi-client-
spec:
  containers:
  - name: yolo-container
    image: niacainfosys/cloud-tfserving-yolo-client
    imagePullPolicy: Always
    command: [sh, -c]
    args: ["python3 grpc_multiclient.py --users=4 --batch_size=30 --iterations=2000 --server=yolo-service:8500"]
  restartPolicy: Never