apiVersion: v1
kind: Pod
metadata:
  generateName: yolo-api-client-
spec:
  containers:
  - name: yolo-container
    image: niacainfosys/cloud-tfserving-yolo-client
    imagePullPolicy: Always
    command: [sh, -c]
    args: ["python3 http_multiclient.py --users=4 --batch_size=30 --iterations=2000 --url=http://yolo-api-service/predict"]
  restartPolicy: Never