apiVersion: v1
kind: Pod
metadata:
  generateName: resnet-client-
spec:
  containers:
  - name: resnet-container
    image: niacainfosys/cloud-tfserving-resnet-client
    imagePullPolicy: Always
    command: [sh, -c]
    args: ["python3 resnet_client_grpc.py --image=cat.jpg --server=resnet-service:8500"]
  restartPolicy: Never