sudo: required

services:
  - docker

before_install:
  - cd tfserving/resnet-client
  - docker build -t niacainfosys/cloud-tfserving-resnet-client -f tfserving-resnet-client.Dockerfile .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push niacainfosys/cloud-tfserving-resnet-client